server:
  port: 8089
spring:
  datasource:
    username: root
    password: EmiYkr132435.
    url: jdbc:mysql://106.54.204.41:3306/schoolshop?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
#    username: root
#    password: 132435
#    url: jdbc:mysql://localhost:3306/schoolshop?useSSL=false&characterEncoding=utf-8&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.swpu.cins.workover.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
file:
  upload-dir: /usr/project/schoolshop/

#log file




