server:
  port: 8089
spring:
  datasource:
    data-username: root
    data-password: 132435
    url: jdbc:mysql://localhost:3306/schoolshop?useSSL=false&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      filters: stat,wall,log4j
  spring:
    http:
      multipart:
        maxFileSize: 10Mb
        maxRequestSize: 10Mb
